config/routes.rb
TMLS::Application.routes.draw do

resources :factories

resources :banks

resources :styles

resources :invoices

resources :users

resources :sessions

resources :customers do
  resources :consignees
end

resources :orders do
 resources :drops do
   resources :items
 end
end

get "reports/index"

get "search/index"

post "orders/acknow"
post "orders/requestacknow"

match '/login',  :to => 'sessions#new'
match '/logout', :to => 'sessions#destroy'

  root :to => 'Sessions#new'

end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  belongs_to :drop
  belongs_to :bank

  attr_accessible :bank_id, :cartoons, :cubic, :date, :drop_id, :factory_invoice, :gross, :hts, :net, :number, :paid, :vat
  default_scope :order => "date, number"

  validates :drop_id,   :presence => true
  validates :bank_id,   :presence => true
  validates :number,    :uniqueness => { :case_sensitive => false },
                        :presence => true
  validates :date,      :presence => true
  validates :cartoons,  :presence => true
  validates :gross,     :presence => true
  validates :net,       :presence => true
  validates :cubic,     :presence => true
  validates :vat,       :presence => true

  def self.search(search)
    if search
      find(:all, :conditions => ["number LIKE ?", "%#{search}%"])
    else
      find(:all)
    end
  end

end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_filter :factory
  before_filter :commercial, :only => [ :create, :destroy, :edit, :new, :update ]

  def index
    @title = "Invoices"
    @invoices = Invoice.search(params[:search])
  end

  def new
    @title = "New Invoice"
    @drop = Drop.find(params[:drop_id])
    @order = @drop.order
    @invoice = @drop.build_invoice
    @invoice.vat ||= "20"
    @invoice.paid ||= 0
  end

  def create
    @invoice = Invoice.new(params[:invoice])
    @drop = @invoice.drop
    @order = @drop.order
    if @invoice.save
      flash[:success] = "Invoice " + @invoice.number.to_s + " created!"
      redirect_to invoice_path(@invoice)
    else
      @title = "New Invoice"
      render 'new'
    end
  end

  def show
    @invoice = Invoice.find(params[:id])
    @title = "Invoice "+ @invoice.number.to_s
  end

  def edit
    @title = "Edit Invoice"
    @invoice = Invoice.find(params[:id])
    @drop = @invoice.drop
    @order = @drop.order
  end

  def update
    @invoice = Invoice.find(params[:id])
    @drop = @invoice.drop
    @order = @drop.order
    if @invoice.update_attributes(params[:invoice])
      flash[:success] = "Invoice details updated!"
      redirect_to invoice_path
    else
      @title = "Edit Invoice"
      render 'edit'
    end
  end

  def destroy
    @invoice = Invoice.find(params[:id])
    @invoice.destroy
    flash[:success] = "Invoice deleted!"
    redirect_to order_path(@invoice.drop.order)
  end

end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/_form.html.erb
<%= form_for(@invoice) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
<div id="form_left">
  <div class="field">
    <%= f.label :number %><br />
    <%= f.text_field :number %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.text_field :date %>
  </div>
  <div class="field">
    <%= f.label :bank %><br />
    <%= f.collection_select(:bank_id, Bank.all, :id, :name , {:include_blank => 'Select Bank Account'} ) %>
  </div>
  <div class="field">
    <%= f.label :paid %><br />
    <%= f.check_box :paid %>
  </div>
  <div class="field">
    <%= f.label :vat %><br />
    <%= f.text_field :vat, :size=>5 %>%
  </div>
  <div class="field">
    <%= f.label :factory_invoice %><br />
    <%= f.text_field :factory_invoice %>
  </div>
</div>
<div id="form_right">
  <div class="field">
    <%= f.label :cartoons %><br />
    <%= f.text_field :cartoons, :size=>5 %>
  </div>
  <div class="field">
    <%= f.label :gross %><br />
    <%= f.text_field :gross, :size=>5 %>KGS
  </div>
  <div class="field">
    <%= f.label :net %><br />
    <%= f.text_field :net, :size=>5 %>KGS
  </div>
  <div class="field">
    <%= f.label :cubic %><br />
    <%= f.text_field :cubic, :size=>5 %>M3
  </div>
  <div class="field">
    <%= f.label :hts, "HTS" %><br />
    <%= f.text_field :hts %>
  </div>
</div>
<div class="clear"></div>
    <%= f.hidden_field :drop_id, :value=>@drop.id %>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/invoices/create.html.erb
<h1>Invoices#create</h1>
<p>Find me in app/views/invoices/create.html.erb</p>

app/views/invoices/destroy.html.erb
<h1>Invoices#destroy</h1>
<p>Find me in app/views/invoices/destroy.html.erb</p>

app/views/invoices/edit.html.erb
<div class="align_right">
  <table class="noborder">
    <tr><th colspan="2">Order Details</th></tr>
    <tr><td>Order No:</td><td><strong><%= @order.number %></strong></td></tr>
    <tr><td>Date:</td><td><strong><%= @order.date.to_formatted_s(:rfc822) %></strong></td></tr>
    <tr><td>Customer:</td><td><strong><%= @order.customer.name %></strong></td></tr>
    <tr><td>Factory:</td><td><strong><%= @order.factory.name %></strong></td></tr>
            <% if @order.currency == 'usd' %>
              <% cur = "$" %>
              <% curdet = "$ USD" %>
            <% elsif @order.currency == 'gbp' %>
              <% cur = "£" %>
              <% curdet = "£ GBP" %>
            <% else @order.currency == 'eur' %>
              <% cur = "€" %>
              <% curdet = "€ EUR" %>
            <% end %>
    <tr><td>Currency:</td><td><strong><%= curdet %></strong></td></tr>
  </table>
        <% avcustomer= @drop.items.sum("customer_price * quantity").to_f / @drop.items.sum("quantity").to_i %>
        <% avfactory= @drop.items.sum("factory_price * quantity").to_f / @drop.items.sum("quantity").to_i %>
        <% finance= @order.finance %>
        <% returns= @order.returns %>
        <% discount= @order.customer.discount %>
        <% terms= avcustomer.to_f * discount.to_f / 100  %>
        <% financing= avcustomer.to_f * finance.to_f / 100  %>
        <% returning= avcustomer.to_f * returns.to_f / 100  %>
        <% gprofit= avcustomer.to_f - avfactory.to_f %>
        <% nprofit= avcustomer.to_f - terms.to_f - financing.to_f - returning.to_f - avfactory.to_f %>
  <table class="noborder">
    <tr><th colspan="2">Summary</th></tr>
    <tr><td>Quantity:</td><td><strong><%= @drop.items.sum("quantity") %></strong></td></tr>
    <tr><td>Customer:</td><td><strong><%= cur %><%= number_with_precision @drop.items.sum("quantity * customer_price"), :precision => 2, :delimiter => ','  %></strong></td></tr>
    <tr><td>Factory:</td><td><strong><%= cur %><%= number_with_precision @drop.items.sum("quantity * factory_price"), :precision => 2, :delimiter => ',' %></strong></td></tr>
  </table>
  <table class="noborder">
  <tr><th colspan="2">Breakdown</th></tr>
  <tr><td>Customer:</td><td class="align_right"><%= number_with_precision avcustomer, :precision => 2, :delimiter => ',' %></td></tr>
  <tr><td>Factory:</td><td class="align_right">-<%= number_with_precision avfactory, :precision => 2, :delimiter => ',' %></td></tr>
  <tr><td><strong>Gross Profit:</strong></td><td class="align_right"><strong><%= number_with_precision gprofit, :precision => 2, :delimiter => ',' %></strong></td></tr>
  <tr><td>Discount (<%= number_with_precision @order.customer.discount, :precision => 2, :delimiter => ',' %>%):</td><td class="align_right">-<%= number_with_precision terms, :precision => 2, :delimiter => ',' %></td></tr>
  <tr><td>Finance (<%= number_with_precision @order.finance, :precision => 2, :delimiter => ',' %>%):</td><td class="align_right">-<%= number_with_precision financing, :precision => 2, :delimiter => ',' %></td></tr>
  <tr><td>Returns (<%= number_with_precision @order.returns, :precision => 2, :delimiter => ',' %>%):</td><td class="align_right">-<%= number_with_precision returning, :precision => 2, :delimiter => ',' %></td></tr>
  <tr><td><strong>Net Profit:</strong></td><td class="align_right"><strong><%= number_with_precision nprofit, :precision => 2, :delimiter => ',' %></strong></td></tr>
</table>
<div class="align_right"><%= button_to "Return to Order", order_path(@order), :method => :get %></div>
</div>

<h1>Edit Invoice</h1>

<%= render 'form' %>

app/views/invoices/index.html.erb
<h1>Invoices</h1>
<div class="align_right">
  <%= form_tag invoices_path, method: :get do %>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", name: nil %>
<% end %>
<br />
</div>
<table class="nospace">
  <tr>
    <th rowspan="2">Date</th>
    <th rowspan="2">Number</th>
    <th colspan="3">GBP</th>
    <th rowspan="2">USD</th>
    <th rowspan="2">EUR</th>
    <th rowspan="2">Customer</th>
    <th rowspan="2">Order No</th>
    <th rowspan="2">Factory</th>
    <th rowspan="2">Factory<br />Invoice</th>
    <th rowspan="2">GBP</th>
    <th rowspan="2">USD</th>
    <th rowspan="2">EUR</th>
    <th rowspan="2">Cartoons</th>
    <th rowspan="2">Quantity</th>
    <th rowspan="2">Gross<br />(KGS)</th>
  </tr>
  <tr>
    <th>Amount</th>
    <th>VAT</th>
    <th>Total</th>
  </tr>
    <% @invoices.each do |invoice| %>
  <tr>
            <% cust = invoice.drop.items.sum("quantity * customer_price") %>
            <% vat = cust * (invoice.vat) * 0.01 %>
            <% totalcust = cust + vat %>
            <% totalfact = invoice.drop.items.sum("quantity * factory_price") %>
    <td><%= invoice.date.to_formatted_s(:rfc822) %></td>
    <td><%= link_to invoice.number, invoice_path(invoice) %></td>
    <% if invoice.drop.order.currency == 'gbp' %>
        <td>£<%= number_with_precision cust, :precision => 2, :delimiter => ','  %></td>
        <td>£<%= number_with_precision vat, :precision => 2, :delimiter => ','  %></td>
        <td>£<%= number_with_precision totalcust, :precision => 2, :delimiter => ','  %></td>
        <td>-</td>
        <td>-</td>
    <% elsif invoice.drop.order.currency == 'usd' %>
        <td>-</td>
        <td>-</td>
        <td>-</td>
        <td>$<%= number_with_precision cust, :precision => 2, :delimiter => ','  %></td>
        <td>-</td>
    <% elsif invoice.drop.order.currency == 'eur' %>
        <td>-</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
        <td>€<%= number_with_precision cust, :precision => 2, :delimiter => ','  %></td>
    <% end %>
    <td><%= invoice.drop.order.customer.name %></td>
    <td class="showhim"><%= link_to invoice.drop.order.number, order_path(invoice.drop.order) %>
      <div class="showme">
            <% avcustomer= invoice.drop.items.sum("customer_price * quantity").to_f / invoice.drop.items.sum("quantity").to_i %>
            <% avfactory= invoice.drop.items.sum("factory_price * quantity").to_f / invoice.drop.items.sum("quantity").to_i %>
            <% finance= invoice.drop.order.finance %>
            <% returns= invoice.drop.order.returns %>
            <% discount= invoice.drop.order.customer.discount %>
            <% terms= avcustomer * discount / 100  %>
            <% financing= avcustomer * finance / 100  %>
            <% returning= avcustomer * returns / 100  %>
            <% gprofit= avcustomer - avfactory %>
            <% nprofit= avcustomer - terms - financing - returning - avfactory %>
          <table>
                <tr><td>Customer:</td><td class="align_right"><%= number_with_precision avcustomer, :precision => 2, :delimiter => ',' %></td></tr>
                <tr><td>Factory:</td><td class="align_right">-<%= number_with_precision avfactory, :precision => 2, :delimiter => ',' %></td></tr>
                <tr><td><strong>Gross Profit:</strong></td><td class="align_right"><strong><%= number_with_precision gprofit, :precision => 2, :delimiter => ',' %></strong></td></tr>
                <tr><td>Discount (<%= number_with_precision invoice.drop.order.customer.discount, :precision => 2, :delimiter => ',' %>%):</td><td class="align_right">-<%= number_with_precision terms, :precision => 2, :delimiter => ',' %></td></tr>
                <tr><td>Finance (<%= number_with_precision invoice.drop.order.finance, :precision => 2, :delimiter => ',' %>%):</td><td class="align_right">-<%= number_with_precision financing, :precision => 2, :delimiter => ',' %></td></tr>
                <tr><td>Returns (<%= number_with_precision invoice.drop.order.returns, :precision => 2, :delimiter => ',' %>%):</td><td class="align_right">-<%= number_with_precision returning, :precision => 2, :delimiter => ',' %></td></tr>
                <tr><td><strong>Net Profit:</strong></td><td class="align_right"><strong><%= number_with_precision nprofit, :precision => 2, :delimiter => ',' %></strong></td></tr>
          </table>
      </div>
    </td>
    <td><%= invoice.drop.order.factory.name %></td>
    <td><%= invoice.factory_invoice %></td>
    <% if invoice.drop.order.currency == 'gbp' %>
        <td>£<%= number_with_precision totalfact, :precision => 2, :delimiter => ','  %></td>
        <td>-</td>
        <td>-</td>
    <% elsif invoice.drop.order.currency == 'usd' %>
        <td>-</td>
        <td>$<%= number_with_precision totalfact, :precision => 2, :delimiter => ','  %></td>
        <td>-</td>
    <% elsif invoice.drop.order.currency == 'eur' %>
        <td>-</td>
        <td>-</td>
        <td>€<%= number_with_precision totalfact, :precision => 2, :delimiter => ','  %></td>
    <% end %>
    <td><%= invoice.cartoons %></td>
    <td><%= invoice.drop.items.sum("quantity") %></td>
    <td><%= invoice.gross %></td>
  <% end %>
  </tr>
</table>

app/views/invoices/new.html.erb
<div class="align_right">
  <table class="noborder">
    <tr><th colspan="2">Order Details</th></tr>
    <tr><td>Order No:</td><td><strong><%= @order.number %></strong></td></tr>
    <tr><td>Date:</td><td><strong><%= @order.date.to_formatted_s(:rfc822) %></strong></td></tr>
    <tr><td>Customer:</td><td><strong><%= @order.customer.name %></strong></td></tr>
    <tr><td>Factory:</td><td><strong><%= @order.factory.name %></strong></td></tr>
            <% if @order.currency == 'usd' %>
              <% cur = "$" %>
              <% curdet = "$ USD" %>
            <% elsif @order.currency == 'gbp' %>
              <% cur = "£" %>
              <% curdet = "£ GBP" %>
            <% else @order.currency == 'eur' %>
              <% cur = "€" %>
              <% curdet = "€ EUR" %>
            <% end %>
    <tr><td>Currency:</td><td><strong><%= curdet %></strong></td></tr>
  </table>
        <% avcustomer= @drop.items.sum("customer_price * quantity").to_f / @drop.items.sum("quantity").to_i %>
        <% avfactory= @drop.items.sum("factory_price * quantity").to_f / @drop.items.sum("quantity").to_i %>
        <% finance= @order.finance %>
        <% returns= @order.returns %>
        <% discount= @order.customer.discount %>
        <% terms= avcustomer.to_f * discount.to_f / 100  %>
        <% financing= avcustomer.to_f * finance.to_f / 100  %>
        <% returning= avcustomer.to_f * returns.to_f / 100  %>
        <% gprofit= avcustomer.to_f - avfactory.to_f %>
        <% nprofit= avcustomer.to_f - terms.to_f - financing.to_f - returning.to_f - avfactory.to_f %>
  <table class="noborder">
    <tr><th colspan="2">Summary</th></tr>
    <tr><td>Quantity:</td><td><strong><%= @drop.items.sum("quantity") %></strong></td></tr>
    <tr><td>Customer:</td><td><strong><%= cur %><%= number_with_precision @drop.items.sum("quantity * customer_price"), :precision => 2, :delimiter => ','  %></strong></td></tr>
    <tr><td>Factory:</td><td><strong><%= cur %><%= number_with_precision @drop.items.sum("quantity * factory_price"), :precision => 2, :delimiter => ',' %></strong></td></tr>
  </table>
  <table class="noborder">
  <tr><th colspan="2">Breakdown</th></tr>
  <tr><td>Customer:</td><td class="align_right"><%= number_with_precision avcustomer, :precision => 2, :delimiter => ',' %></td></tr>
  <tr><td>Factory:</td><td class="align_right">-<%= number_with_precision avfactory, :precision => 2, :delimiter => ',' %></td></tr>
  <tr><td><strong>Gross Profit:</strong></td><td class="align_right"><strong><%= number_with_precision gprofit, :precision => 2, :delimiter => ',' %></strong></td></tr>
  <tr><td>Discount (<%= number_with_precision @order.customer.discount, :precision => 2, :delimiter => ',' %>%):</td><td class="align_right">-<%= number_with_precision terms, :precision => 2, :delimiter => ',' %></td></tr>
  <tr><td>Finance (<%= number_with_precision @order.finance, :precision => 2, :delimiter => ',' %>%):</td><td class="align_right">-<%= number_with_precision financing, :precision => 2, :delimiter => ',' %></td></tr>
  <tr><td>Returns (<%= number_with_precision @order.returns, :precision => 2, :delimiter => ',' %>%):</td><td class="align_right">-<%= number_with_precision returning, :precision => 2, :delimiter => ',' %></td></tr>
  <tr><td><strong>Net Profit:</strong></td><td class="align_right"><strong><%= number_with_precision nprofit, :precision => 2, :delimiter => ',' %></strong></td></tr>
</table>
<div class="align_right"><%= button_to "Return to Order", order_path(@order), :method => :get %></div>
</div>

<h1>New Invoice</h1>

<%= render 'form' %>

app/views/invoices/show.html.erb
<div class="noprint">
  <br /><br />
  <% unless current_user.department == "Commercial" %>
  <p class="align_right"><%= link_to "edit invoice", edit_invoice_path %> |
    <%= link_to "delete invoice", @invoice, confirm: 'Invoice ' + @invoice.number + ' will be deleted! Are you sure you want to delete it?', method: :delete %> |
    <input type="button"
        onClick="window.print()"
        value="Print Invoice"/>
  </p>
  <% end %>
  <p class="button_invoice" style="float: left;"><%= link_to "Return to Order", order_path(@invoice.drop.order), :method=> :get %></p>
  <div class="clear"></div>
</div>
<div id="invoice">
  <p><strong>TMLS SERVICES LTD</strong></p>
  <p class="smaller">32, North End Road , West Kensington, London, W14 OSH, UK</p>
  <p class="smaller">Tel: 02073713503 | 02073712706 Fax: 02073716322 <span class="align_right">VAT No .843934701</span></p>

  <div class="invoice_title"><strong>COMMERCIAL INVOICE</strong></div>
  <div class="align_right"><%= @invoice.date.to_formatted_s(:rfc822) %></div>
  <table>
    <tr><th>INVOICE:</th><td><%= @invoice.number %></td></tr>
  </table>

  <table class="float_left">
    <tr><th>APPLICANT:</th><td><%= @invoice.drop.order.customer.name %></td></tr>
    <tr><th></th><td><%= @invoice.drop.order.customer.address1 %></td></tr>
    <tr><th></th><td><%= @invoice.drop.order.customer.address2 %></td></tr>
    <tr><th></th><td><%= @invoice.drop.order.customer.city %></td></tr>
    <tr><th></th><td><%= @invoice.drop.order.customer.postcode %></td></tr>
    <tr><th></th><td><%= @invoice.drop.order.customer.country %></td></tr>
  </table>

  <table class="align_right">
    <tr><th>CONSIGNEE:</th><td><%= @invoice.drop.consignee.name %></td></tr>
    <tr><th></th><td><%= @invoice.drop.consignee.address1 %>, <%= @invoice.drop.consignee.address2 %></td></tr>
    <tr><th></th><td><%= @invoice.drop.consignee.city %>, <%= @invoice.drop.consignee.postcode %></td></tr>
    <tr><th></th><td><%= @invoice.drop.consignee.country %></td></tr>
  </table>

  <table class="align_right">
    <tr><th>FACTORY:</th><td><%= @invoice.drop.order.factory.name %></td></tr>
    <tr><th></th><td><%= @invoice.drop.order.factory.address1 %>, <%= @invoice.drop.order.factory.address2 %></td></tr>
    <tr><th></th><td><%= @invoice.drop.order.factory.city %>, <%= @invoice.drop.order.factory.postcode %>, <%= @invoice.drop.order.factory.country %></td></tr>
  </table>

  <table class="float_left">
    <tr><th>ORIGIN OF GOODS:</th><td><%= @invoice.drop.order.factory.country %></td></tr>
  </table>

  <table class="float_left">
    <tr><th>HTS CODE:</th><td><%= @invoice.hts %></td></tr>
  </table>

  <table class="align_right">
    <tr><th>PURCHASE ORDER:</th><td><%= @invoice.drop.order.number %></td></tr>
  </table>
  <div class="clear"></div>

  <div class="invoice_title">DESCRIPTION OF GOODS</div>

  <p><%= pluralize(@invoice.cartoons, 'CORRUGATED CARTON').upcase %>  CONTAINING <%= pluralize(@invoice.drop.items.sum("quantity"), 'PAIR').upcase %> OF LADIES FOOTWEAR</p>
  <div id="products_invoice">
            <% if @invoice.drop.order.currency == 'usd' %>
              <% cur = "$" %>
            <% elsif @invoice.drop.order.currency == 'gbp' %>
              <% cur = "£" %>
            <% else @invoice.drop.order.currency == 'eur' %>
              <% cur = "€" %>
            <% end %>
    <table>
      <tr>
        <th>COLOUR</th>
        <th>STYLE NO</th>
        <th>CUSTOMER<br />STYLE</th>
        <th>LINE NO</th>
        <th>MATERIAL</th>
        <th>MDA</th>
        <th>PAIRS</th>
        <th style="text-align: right">PRICE (<%= cur %>)</th>
        <th style="text-align: right">TOTAL (<%= cur %>)</th>
      </tr>
      <% @invoice.drop.items.each do |item| %>
      <tr>
        <td><%= item.colour.upcase %></td>
        <td><%= item.style.style.upcase %></td>
        <td><%= item.customer_style.upcase %></td>
        <td><%= item.line_number.upcase %></td>
        <td><%= item.upper.upcase %></td>
        <td><%= item.mda %></td>
        <td style="text-align: right"><%= item.quantity %></td>
        <td style="text-align: right"><%= cur %><%= number_with_precision item.customer_price, :precision => 2, :delimiter => ',' %></td>
        <td style="text-align: right"><%= cur %><%= number_with_precision (item.customer_price * item.quantity), :precision => 2, :delimiter => ',' %></td>
      </tr>
      <% end %>

        <% if cur == '£' and @invoice.vat != 0 %>
          <% net = @invoice.drop.items.sum("quantity * customer_price").to_f %>
          <% vat = (@invoice.vat) * 0.01 * net%>
          <tr>
            <td colspan="7"></td><td style="text-align: right"><strong>TOTAL NET</strong></td><td style="text-align: right"><strong><%= cur %><%= number_with_precision net, :precision => 2, :delimiter => ',' %></strong></td>
          </tr>
          <tr>
            <td colspan="7"></td><td style="text-align: right"><strong>VAT (<%= number_with_precision @invoice.vat, :precision => 2, :delimiter => ',' %>%)</strong></td><td style="text-align: right"><strong><%= cur %><%= number_with_precision vat, :precision => 2, :delimiter => ',' %></strong></td>
          </tr>
          <tr>
            <th colspan="6">TOTAL</th><th style="text-align: right"><%= @invoice.drop.items.sum("quantity") %></th><th></th><th style="text-align: right"><%= cur %><%= number_with_precision net + vat, :precision => 2, :delimiter => ',' %></th>
          </tr>
        <% else %>
          <tr>
            <th rowspan="2" colspan="6">TOTAL</th><th style="text-align: right"><%= @invoice.drop.items.sum("quantity") %></th><th style="text-align: right">TOTAL FOB <%= @invoice.drop.order.factory.country %></th><th style="text-align: right"><%= cur %><%= number_with_precision (@invoice.drop.items.sum("quantity * customer_price")), :precision => 2, :delimiter => ',' %></th>
          </tr>
        <% end %>
    </table>
  </div>
  <div id="invoice_payment">
      <table>
        <tr><th>SAY:</th><td></td></tr>
      </table>

      <table>
        <tr><th>TERMS:</th><td><%= simple_format(@invoice.drop.order.customer.terms.upcase) %></td></tr>
      </table>

      <% unless @invoice.bank.notice.nil? or @invoice.bank.notice == '' %>
        <table>
          <tr><th>NOTICE OF ASSIGNMENT:</th><td><%= simple_format(@invoice.bank.notice.upcase) %></td></tr>
        </table>
      <% end %>

      <table>
        <tr><th>BANK DETAILS:</th><td><strong><%= simple_format(@invoice.bank.name.upcase) %></strong></td></tr>
        <% unless @invoice.bank.address.nil? or @invoice.bank.address == '' %>
          <tr><th></th><td><%= simple_format(@invoice.bank.address.upcase) %></td></tr>
        <% end %>
      </table>
      <table>
        <tr><th class="thbank">SORT CODE:</th><td><%= @invoice.bank.sort_code.upcase %></td></tr>
        <tr><th class="thbank">ACCOUNT:</th><td><%= @invoice.bank.account.upcase %></td></tr>
        <% unless @invoice.bank.iban.nil? or @invoice.bank.iban == '' %>
          <tr><th class="thbank">IBAN:</th><td><%=@invoice.bank.iban.upcase %></td></tr>
        <% end %>
        <% unless @invoice.bank.swift.nil? or @invoice.bank.swift == '' %>
          <tr><th class="thbank">SWIFT:</th><td><%=@invoice.bank.swift.upcase %></td></tr>
        <% end %>
        <% unless @invoice.bank.bic.nil? or @invoice.bank.bic == '' %>
          <tr><th class="thbank">BIC:</th><td><%=@invoice.bank.bic.upcase %></td></tr>
        <% end %>
      </table>

      <table>
        <tr><th>PROPERTY AND RISK:</th><td><p>IN SPITE OF DELIVERY HAVING BEEN MADE, PROPERTY IN THE PRODUCTS SHALL NOT PASS FROM THE COMPANY UNTIL:</p></td></tr>
        <tr><th></th><td><p>1- THE CUSTOMER SHALL HAVE PAID THE PRICE PLUS VAT IN FULL;</p></td></tr>
        <tr><th></th><td><p>2- NO OTHER SUMS WHATEVER SHALL BE DUE FROM THE CUSTOMER TO THE COMPANY.</p></td></tr>
      </table>

      <table>
        <tr><th></th><td>GROSS WEIGHT: <%= @invoice.gross %> KGS<span class="marginleft">NET WEIGHT: <%= @invoice.net %> KGS</span><span class="marginleft">CUBIC METERS: <%= @invoice.cubic %> M3</span></td></tr>
      </table>
  </div>
</div>

app/views/invoices/update.html.erb
<h1>Invoices#update</h1>
<p>Find me in app/views/invoices/update.html.erb</p>