config/routes.rb
TMLS::Application.routes.draw do

resources :factories

resources :banks

resources :styles

resources :invoices

resources :users

resources :sessions

resources :customers do
  resources :consignees
end

resources :orders do
 resources :drops do
   resources :items
 end
end

get "reports/index"

get "search/index"

post "orders/acknow"
post "orders/requestacknow"

match '/login',  :to => 'sessions#new'
match '/logout', :to => 'sessions#destroy'

  root :to => 'Sessions#new'

end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :factory

  attr_accessible :admin, :department, :email, :factory_id, :name, :password, :password_confirmation
  has_secure_password

  validates :name,        :uniqueness => { :case_sensitive => false },
                          :presence => true
  validates :email,       :uniqueness => { :case_sensitive => false },
                          :presence => true,
                          :format   => { :with => /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :password,    :presence => true
  validates :department,  :presence => true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :admin, only: [:new, :create, :index, :destroy ]

  def index
    @title = "Manage Users"
    @users=User.all
  end

  def show
    @title = "Home"
    if current_user.nil?
      redirect_to login_path
    elsif current_user.department == "Factory"
      factory = current_user.factory
      @orders = factory.orders
      @orders = @orders.find_all_by_acknowledgement(false)
    end
  end

  def new
    @title = "New User"
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:success] = "User " + @user.name + " created!"
      redirect_to users_url
    else
      @title = "New User"
      render "new"
    end
  end

  def edit
    @title = "Edit User"
    if current_user.admin?
      @user = User.find(params[:id])
    else
      @user = current_user
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:success] = "User details updated!"
        if current_user.admin?
          redirect_to users_path
        else
          redirect_to user_path
        end
    else
      @title = "Edit User"
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user == current_user
      flash[:error] = "User can't be deleted"
      redirect_to users_path
    else
      @user.destroy
      flash[:success] = "User deleted!"
      redirect_to users_path
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :department %><br />
        <%= f.radio_button :department, "Commercial" %>
        <%= f.label :commercial %><br />
        <%= f.radio_button :department, "Accounts" %>
        <%= f.label :accounts %><br />
        <%= f.radio_button :department, "Factory" %>
        <%= f.label :factory %>
  </div>
  <div class="field">
    <%= f.label :factory %><br />
    <%= f.collection_select(:factory_id, Factory.all, :id, :name , {:include_blank => 'Select Factory'} ) %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :admin %><br />
    <%= f.check_box :admin %>
  </div>
<div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_password.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>

  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
<div class="actions">
    <%= f.submit "Save Password" %>
  </div>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<% if @user == current_user %>
    <h1>New Password</h1>
    <%= render 'password' %>
<% else %>
    <h1>Edit User <%= @user.name %> </h1>
    <%= render 'form' %>
<% end %>

app/views/users/index.html.erb
<h1>Users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Department</th>
    <th>Email</th>
    <th>Admin?</th>
    <td colspan="2"></td>
  </tr>
    <% @users.each do |user| %>
    <% if user.admin? %>
    <% temp = 'yes' %>
    <% else %>
    <% temp = 'no' %>
    <% end %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.department %></td>
    <td><%= user.email %></td>
    <td><%= temp %></td>
    <td><%= link_to "edit", edit_user_path(user) %> |</td>
    <td><%= link_to 'delete', user, confirm: user.name + ' will be deleted! Are you sure you want to delete it?', method: :delete %></td>
  </tr>
    <% end %>
</table>
<%= link_to "Create new user", new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<div class="float_left">
<h1>Home</h1>

</div>


<div class = "align_right">
  <%= link_to "Change your password", edit_user_path %>
<% if current_user.admin? %> |
  <%= link_to "Manage Users", users_path %>
<% end %>
</div>
<br /> <br /> <br />


<div class="align_right">
  <%= form_tag orders_path, method: :get do %>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Find Order", name: nil %>
<% end %>
  <% unless current_user.department == "Factory" %>
<br />
  <%= form_tag styles_path, method: :get do %>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Find Style|Construction", name: nil %>
<% end %>
<br />
  <%= form_tag invoices_path, method: :get do %>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Find Invoice", name: nil %>
<% end %>
    <br /><%= link_to "Advanced Search", search_index_path %>
  <% end %>
</div>
<div class="clear"></div>

<% unless current_user.department != "Factory" %>
<h3>Orders to be acknowledged</h3>
<table>
  <tr>
    <th>Customer</th>
    <th>Order No</th>
    <th>Order Date</th>
    <th>Quantity</th>
    <th>Factory</th>
    <th>Amount</th>
    <th>Latest XF Date</th>
    <th>Order Status</th>
    <th>Last Acknowl.</th>
    <td></td>
  </tr>
    <% @orders.each do |order| %>

      <% if order.currency == 'usd' %>
        <% cur = "$" %>
      <% elsif order.currency == 'gbp' %>
        <% cur = "£" %>
      <% else order.currency == 'eur' %>
        <% cur = "€" %>
      <% end %>

  <tr class="bigtr">
    <td><%= order.customer.name %></td>
    <td><%= link_to order.number, order_path(order) %></td>
    <td><%= order.date.to_formatted_s(:rfc822) %></td>
        <% tquantity= order.drops.map do |i| i.items.sum("quantity") end.sum %>
    <td><%= tquantity %></td>
    <td><%= order.factory.name %></td>
        <% tfactory= order.drops.map do |i| i.items.sum("quantity * factory_price").to_f end.sum %>
    <td><%= cur %><%= number_with_precision tfactory, :precision => 2, :delimiter => ',' %></td>
    <% if order.drops.count == 0 %>
      <% if current_user.department == "Factory" %>
        <td>-</td>
      <% else %>
        <td>-</td>
        <td>-</td>
      <% end %>
    <% else %>
      <td><%= order.drops.maximum("factory_date").to_formatted_s(:rfc822) %></td>
    <% end %>
    <td></td>
    <% if order.acknowledgementdate.nil? %>
      <td>-</td>
    <% else %>
      <td><%= order.acknowledgementdate.to_formatted_s(:rfc822) %></td>
    <% end %>
    <% if current_user.department == "Factory" %>
      <% unless order.acknowledgement == true %>
        <td><%= button_to "Acknowledge", :controller=>"orders", :action => "acknow", :id=>order.id %></td>
      <% end %>
    <% else %>

    <% end %>
  </tr>
  <% end %>
</table>
<% end %>