config/routes.rb
TMLS::Application.routes.draw do

resources :factories

resources :banks

resources :styles

resources :invoices

resources :users

resources :sessions

resources :customers do
  resources :consignees
end

resources :orders do
 resources :drops do
   resources :items
 end
end

get "reports/index"

get "search/index"

post "orders/acknow"
post "orders/requestacknow"

match '/login',  :to => 'sessions#new'
match '/logout', :to => 'sessions#destroy'

  root :to => 'Sessions#new'

end

app/models/factory.rb
class Factory < ActiveRecord::Base
  has_many :orders
  has_one :user

  attr_accessible :address1, :address2, :city, :contact, :country, :email, :name, :postcode, :telephone
  default_scope :order => "country, name"

  validates :name,      :uniqueness => { :case_sensitive => false },
                        :presence => true
  validates :contact,   :presence => true
  validates :email,     :uniqueness => { :case_sensitive => false },
                        :presence => true,
                        :format   => { :with => /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :country,   :presence => true
end

app/controllers/factories_controller.rb
class FactoriesController < ApplicationController
  before_filter :factory
  before_filter :commercial, :only => [ :create, :destroy, :edit, :new, :update ]

  def index
    @title = "Factories"
    @factories = Factory.all
  end

  def new
    @title = "New Factory"
    @factory = Factory.new
  end

  def create
    @factory=Factory.new(params[:factory])
    if @factory.save
      flash[:success] = "Factory " + @factory.name + " created!"
      redirect_to factories_path
    else
      @title = "New Factory"
      render 'new'
    end
  end


  def edit
    @title = "Edit Factory"
    @factory = Factory.find(params[:id])
  end

  def update
    @factory = Factory.find(params[:id])
    if @factory.update_attributes(params[:factory])
      flash[:success] = "Factory details updated!"
      redirect_to factories_path
    else
      @title = "Edit Factory"
      render 'edit'
    end
  end

  def destroy
    @factory = Factory.find(params[:id])
    if @factory.orders.count == 0
      @factory.destroy
      flash[:success] = "Factory deleted!"
      redirect_to factories_path
    else
      flash[:error] = "Factory can't be deleted, there are orders related to this factory"
      redirect_to factories_path
    end
  end

end

app/helpers/factories_helper.rb
module FactoriesHelper
end

app/views/factories/_form.html.erb
<%= form_for(@factory) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address1, "Address Line 1" %><br />
    <%= f.text_field :address1 %>
  </div>
  <div class="field">
    <%= f.label :address2, "Address Line 2" %><br />
    <%= f.text_field :address2 %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :postcode %><br />
    <%= f.text_field :postcode %>
  </div>
  <div class="field">
    <%= f.label :country %><br />
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :contact %><br />
    <%= f.text_field :contact %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :telephone %><br />
    <%= f.text_field :telephone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/factories/edit.html.erb
<h1>Edit Factory <%= @factory.name %></h1>
<%= render 'form' %>

app/views/factories/index.html.erb
<h1>Factories</h1>

<table>
  <tr>
    <th rowspan="2">Name</th>
    <th rowspan="2">Country</th>
    <th rowspan="2">Details</th>
    <th colspan="4">Orders Summary</th>
    <% unless current_user.department == "Commercial" %>
    <td rowspan="2"></td>
    <td rowspan="2"></td>
    <% end %>
  </tr>
  <tr>
    <th>Shipped</th>
    <th>Part Shipped</th>
    <th>In Production</th>
    <th>Total</th>
  </tr>
    <% @factories.each do |factory| %>
  <tr>
    <td><%= factory.name %></td>
    <td><%= factory.country %></td>
    <td class="showhim">Details
        <div class="showme">
            <p><strong><%= factory.name %></strong></p>
            <p><%= factory.contact %></p>
            <p><%= factory.address1 %><br />
            <%= factory.address2 %><br />
            <%= factory.city %><br />
            <%= factory.country %><br />
            <%= factory.postcode %><br /><br />
            <%= mail_to factory.email %><br />
            <%= factory.telephone %></p>
        </div>
    </td>
          <% shipped = 0 %>
          <% partshipped = 0 %>
          <% inproduction = 0 %>
      <% factory.orders.each do |order| %>
        <% if order.status(order) == "Shipped" %>
          <% shipped = shipped + 1 %>
        <% elsif order.status(order) == "Part Shipped" %>
          <% partshipped = partshipped + 1 %>
        <% else %>
          <% inproduction = inproduction + 1 %>
        <% end %>
      <% end %>
    <td class="centre"><%= shipped %></td>
    <td class="centre"><%= partshipped %></td>
    <td class="centre"><%= inproduction %></td>
    <td class="centre"><%= factory.orders.count %></td>
    <% unless current_user.department == "Commercial" %>
    <td><%= link_to "edit", edit_factory_path(factory) %></td>
    <td><%= link_to 'delete', factory, confirm: factory.name + ' will be deleted! Are you sure you want to delete it?', method: :delete %></td>
    <% end %>
  </tr>
    <% end %>
</table>
<% unless current_user.department == "Commercial" %>
<p><%= link_to "New Factory", new_factory_path %></p>
<% end %>

app/views/factories/new.html.erb
<h1>New Factory</h1>

<%= render 'form' %>