config/routes.rb
TMLS::Application.routes.draw do

resources :factories

resources :banks

resources :styles

resources :invoices

resources :users

resources :sessions

resources :customers do
  resources :consignees
end

resources :orders do
 resources :drops do
   resources :items
 end
end

get "reports/index"

get "search/index"

post "orders/acknow"
post "orders/requestacknow"

match '/login',  :to => 'sessions#new'
match '/logout', :to => 'sessions#destroy'

  root :to => 'Sessions#new'

end

app/models/style.rb
class Style < ActiveRecord::Base
  has_many :items

  attr_accessible :construction, :image, :style
  mount_uploader :image, ImageUploader
  default_scope :order => "style, construction"

  validates :style,           :presence => true,
                              :uniqueness => {:scope => :construction, :message => "/ Construction combination has already been taken"}
  validates :construction,    :presence => true
  validates :image,           :presence => true

  def dropdown
    "#{style} | #{construction}"
  end

  def self.search(search)
    if search
      find(:all, :conditions => ["style LIKE ? OR construction LIKE ?", "%#{search}%", "%#{search}%"])
    else
      find(:all)
    end
  end
end

app/controllers/styles_controller.rb
class StylesController < ApplicationController
  before_filter :factory

  def index
      @title = "Styles"
      @styles = Style.search(params[:search])
    end

    def new
      @title = "New Style"
      @style = Style.new
    end

    def create
      @style=Style.new(params[:style])
      if @style.save
        flash[:success] = "Style " + @style.style + "|" + @style.construction + " created!"
        redirect_to styles_path
      else
        @title = "New Style"
        render 'new'
      end
    end

    def edit
      @title = "Edit Style"
      @style = Style.find(params[:id])
    end

    def update
      @style = Style.find(params[:id])
      if @style.update_attributes(params[:style])
        flash[:success] = "Style details updated!"
        redirect_to styles_path
      else
        @title = "Edit Style"
        render 'edit'
      end
    end

    def destroy
      @style = Style.find(params[:id])
      if @style.items.count == 0
        @style.destroy
        flash[:success] = "Style deleted!"
        redirect_to styles_path
      else
        flash[:error] = "Style can't be deleted, there are items related to this style"
        redirect_to styles_path
      end
    end

end

app/helpers/styles_helper.rb
module StylesHelper
end

app/views/styles/_form.html.erb
<%= form_for(@style) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :style %><br />
    <%= f.text_field :style %>
  </div>
  <div class="field">
    <%= f.label :construction %><br />
    <%= f.text_field :construction %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/styles/create.html.erb
<h1>Styles#create</h1>
<p>Find me in app/views/styles/create.html.erb</p>

app/views/styles/destroy.html.erb
<h1>Styles#destroy</h1>
<p>Find me in app/views/styles/destroy.html.erb</p>

app/views/styles/edit.html.erb
<h1>Edit Style</h1>

<%= render 'form' %>

app/views/styles/index.html.erb
<h1>Styles</h1>
<div class="align_right">
  <%= form_tag styles_path, method: :get do %>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", name: nil %>
<% end %>
<br />
</div>

<table>
  <tr>
    <th>Picture</th>
    <th>Style</th>
    <th>Construction</th>
    <td></td>
  </tr>
    <% @styles.each do |style| %>
  <tr>
    <td class="showhim"><%= image_tag style.image_url(:thumb).to_s %>
      <div class="showme"><%= image_tag style.image_url.to_s %></div>
    </td>
    <td><%= style.style %></td>
    <td><%= style.construction %></td>
    <td><%= link_to "edit", edit_style_path(style) %> |
        <%= link_to 'delete', style, confirm: 'Style ' + style.style + "|" + style.construction  + ' will be deleted! Are you sure you want to delete it?', method: :delete %>
    </td>
  </tr>
    <% end %>
</table>
<p><%= link_to "New Style", new_style_path %></p>

app/views/styles/new.html.erb
<h1>New Style</h1>

<%= render 'form' %>